export const productCategories = {
  crop_nutrition: "Fertilisers & Crop Nutrition",
  seeds: "Seeds",
  crop_protection: "Pesticides & Crop Protection",
  soil_health: "Organic Manure & Soil Health",
  irrigation: "Irrigation & Watering",
  tools: "Farm Tools & Equipment",
  nursery: "Nursery Supplies",
  safety: "Safety Gear",
  post_harvest: "Post-Harvest Supplies",
} as const;

export type ProductCategory = keyof typeof productCategories;

export type CatalogueProduct = {
  id: number;
  name: string;
  category: ProductCategory;
  shortDescription: string;
  description: string;
  specs: string;
  bestSuitedFor: string;
  usageTip: string;
  safetyNote: string;
  packSizes: string;
  imageUrl: string;
  featured: boolean;
  activeIngredient?: string;
  formulation?: string;
  targetUse?: string;
  registeredCropUse?: string;
  pcpbStatus?: string;
  phi?: string;
  rei?: string;
  ppe?: string;
  storageWarning?: string;
  createdAt: Date;
  updatedAt: Date;
};

const now = new Date("2026-05-27T09:00:00.000Z");

function product(
  id: number,
  product: Omit<CatalogueProduct, "id" | "createdAt" | "updatedAt">,
): CatalogueProduct {
  return {
    id,
    createdAt: new Date(2026, 4, Math.max(1, 27 - id)),
    updatedAt: now,
    ...product,
  };
}

export const starterProducts: CatalogueProduct[] = [
  product(1, {
    name: "DAP 18-46-0 Fertiliser",
    category: "crop_nutrition",
    shortDescription: "Planting fertiliser commonly used to support early root development.",
    description: "DAP is a widely used planting fertiliser for cereals, legumes, and many field crops where phosphorus is needed early in crop establishment.",
    specs: "18-46-0 NPK",
    bestSuitedFor: "Maize, beans, wheat, cereals, and many crops at planting stage",
    usageTip: "Commonly used at planting where phosphorus is needed for early root development. Avoid direct seed contact and follow agronomic guidance.",
    safetyNote: "Fertiliser recommendations depend on crop type, soil condition, rainfall, region, and previous farm management.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/dap-fertiliser.webp",
    featured: true,
  }),
  product(2, {
    name: "CAN 26/27% Nitrogen Fertiliser",
    category: "crop_nutrition",
    shortDescription: "Top-dressing nitrogen fertiliser for active crop growth.",
    description: "Calcium Ammonium Nitrate supplies nitrogen and calcium for established crops during vegetative growth.",
    specs: "Calcium Ammonium Nitrate, commonly 26-27% nitrogen",
    bestSuitedFor: "Maize, vegetables, potatoes, wheat, pasture, and general top-dressing",
    usageTip: "Good for top dressing after crop establishment when the crop can use nitrogen effectively.",
    safetyNote: "Apply when soil has moisture and follow local agronomist guidance.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/can-fertiliser.webp",
    featured: true,
  }),
  product(3, {
    name: "Urea 46-0-0 Fertiliser",
    category: "crop_nutrition",
    shortDescription: "High-nitrogen fertiliser for cereals, pasture, and leafy crops.",
    description: "Urea is a concentrated nitrogen fertiliser used where crops need strong vegetative growth support.",
    specs: "46-0-0 NPK",
    bestSuitedFor: "Maize, cereals, pasture, and leafy crops",
    usageTip: "Best applied when soil moisture is available or rain is expected to reduce nitrogen losses.",
    safetyNote: "Avoid leaving exposed on hot or dry soil and seek guidance on correct timing.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/urea-fertiliser.webp",
    featured: true,
  }),
  product(4, {
    name: "NPK 17-17-17 Fertiliser",
    category: "crop_nutrition",
    shortDescription: "Balanced crop nutrition for vegetables, potatoes, and mixed farming.",
    description: "Balanced NPK fertiliser supports crops where nitrogen, phosphorus, and potassium are all required.",
    specs: "17-17-17 NPK",
    bestSuitedFor: "Vegetables, potatoes, fruiting crops, and general crop nutrition",
    usageTip: "Useful where crops need balanced nutrients, especially in vegetable production.",
    safetyNote: "Soil-test advice gives better results than one-size-fits-all application.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/npk-17-17-17.webp",
    featured: true,
  }),
  product(5, {
    name: "NPK 23-23-0 Fertiliser",
    category: "crop_nutrition",
    shortDescription: "Nitrogen and phosphorus fertiliser for early crop development.",
    description: "NPK 23-23-0 provides nitrogen and phosphorus and is often used as a planting fertiliser where potassium is not limiting.",
    specs: "23-23-0 NPK",
    bestSuitedFor: "Maize, cereals, and planting programmes in suitable soils",
    usageTip: "Often used as a planting fertiliser alternative to DAP in some maize-growing regions.",
    safetyNote: "Confirm soil fertility needs before selecting fertiliser type.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/npk-23-23-0.webp",
    featured: false,
  }),
  product(6, {
    name: "NPK 15-15-15 Fertiliser",
    category: "crop_nutrition",
    shortDescription: "General-purpose balanced NPK fertiliser.",
    description: "NPK 15-15-15 is a balanced fertiliser option for horticulture, vegetables, and garden crops.",
    specs: "15-15-15 NPK",
    bestSuitedFor: "Vegetables, horticulture, and general garden crops",
    usageTip: "Useful where balanced nutrition is required across mixed crops.",
    safetyNote: "Use according to crop stage and soil fertility needs.",
    packSizes: "1kg, 2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/npk-15-15-15.webp",
    featured: false,
  }),
  product(7, {
    name: "Calcium Nitrate",
    category: "crop_nutrition",
    shortDescription: "Calcium and nitrate nitrogen support for high-value crops.",
    description: "Calcium nitrate supports calcium nutrition in actively growing and fruiting crops.",
    specs: "Nitrate nitrogen plus calcium",
    bestSuitedFor: "Tomatoes, capsicum, watermelon, cucumber, fruits, and leafy vegetables",
    usageTip: "Useful where calcium demand is high, especially in fruiting vegetables.",
    safetyNote: "Avoid cure claims; calcium nutrition results depend on crop and farm conditions.",
    packSizes: "1kg, 2kg, 10kg, 25kg depending on stock",
    imageUrl: "/images/products/calcium-nitrate.webp",
    featured: true,
  }),
  product(8, {
    name: "Potassium Nitrate",
    category: "crop_nutrition",
    shortDescription: "Soluble potassium nutrition for flowering and fruiting stages.",
    description: "Potassium nitrate is commonly used where crops need potassium and nitrogen during fruiting and bulking stages.",
    specs: "Common soluble grade around 13-0-46",
    bestSuitedFor: "Tomatoes, onions, potatoes, fruits, flowering and fruiting crops",
    usageTip: "Good for stages where potassium demand is high.",
    safetyNote: "Use according to agronomic advice and avoid over-application.",
    packSizes: "1kg, 2kg, 10kg, 25kg depending on stock",
    imageUrl: "/images/products/potassium-nitrate.webp",
    featured: false,
  }),
  product(9, {
    name: "Potassium Sulphate / SOP",
    category: "crop_nutrition",
    shortDescription: "Potassium and sulphur source for chloride-sensitive crops.",
    description: "SOP supplies potassium without chloride and is useful for high-value horticultural crops.",
    specs: "Often 0-0-50 or similar potassium source with sulphur",
    bestSuitedFor: "Potatoes, onions, fruits, vegetables, and chloride-sensitive crops",
    usageTip: "Good premium horticulture stock item where farmers need potassium without chloride.",
    safetyNote: "Application should follow crop and soil needs.",
    packSizes: "1kg, 2kg, 10kg, 25kg depending on stock",
    imageUrl: "/images/products/potassium-sulphate.webp",
    featured: false,
  }),
  product(10, {
    name: "Agricultural Lime",
    category: "soil_health",
    shortDescription: "Soil acidity management product for acidic soils.",
    description: "Agricultural lime helps manage soil acidity where soil testing confirms lime is needed.",
    specs: "Calcium carbonate / liming material",
    bestSuitedFor: "Acidic soils, maize zones, tea zones, Western Kenya and Rift Valley depending on soil test",
    usageTip: "Sell with a soil-test-first message because lime rate depends on soil pH and lime requirement.",
    safetyNote: "Do not apply blindly; soil testing is strongly recommended.",
    packSizes: "2kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/agricultural-lime.webp",
    featured: true,
  }),
  product(11, {
    name: "Organic Manure / Compost",
    category: "soil_health",
    shortDescription: "Organic matter for improving soil structure and moisture retention.",
    description: "Well-prepared compost improves soil organic matter, structure, water retention, and biological activity.",
    specs: "Decomposed organic matter",
    bestSuitedFor: "Soil improvement, vegetables, maize, fruit trees, and nursery mixes",
    usageTip: "Best used together with balanced fertiliser where nutrient demand is high.",
    safetyNote: "Use mature compost and avoid contaminated materials.",
    packSizes: "5kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/organic-manure.webp",
    featured: true,
  }),
  product(12, {
    name: "Poultry Manure",
    category: "soil_health",
    shortDescription: "Composted poultry manure for crop and soil nutrition.",
    description: "Poultry manure is an organic nutrient source commonly used for vegetables, maize, bananas, and fruit trees.",
    specs: "Organic manure, usually higher in nitrogen than many farmyard manures",
    bestSuitedFor: "Vegetables, maize, bananas, and fruit trees",
    usageTip: "Must be well composted before use.",
    safetyNote: "Fresh manure can burn crops and may carry pathogens or weed seeds.",
    packSizes: "5kg, 10kg, 25kg, 50kg depending on stock",
    imageUrl: "/images/products/poultry-manure.webp",
    featured: false,
  }),
  product(13, {
    name: "Rhizobia Inoculant",
    category: "soil_health",
    shortDescription: "Biofertiliser inoculant for legume seed coating.",
    description: "Rhizobia inoculants support legume nodulation when used correctly at planting.",
    specs: "Legume inoculant for seed coating",
    bestSuitedFor: "Beans, peas, soybeans, groundnuts, cowpeas, and green grams",
    usageTip: "Used to coat legume seed just before planting so rhizobia are available when roots emerge.",
    safetyNote: "Keep inoculants cool and follow product handling instructions.",
    packSizes: "Small sachets and packets depending on brand",
    imageUrl: "/images/products/rhizobia-inoculant.webp",
    featured: false,
  }),
  product(14, {
    name: "Foliar Micronutrient Mix",
    category: "crop_nutrition",
    shortDescription: "Trace-element support for crops during high-demand stages.",
    description: "Foliar micronutrient mixes support crop nutrition where deficiencies or high demand are identified.",
    specs: "Trace elements such as Zn, B, Mg, Mn, Fe, and Mo depending on brand",
    bestSuitedFor: "Vegetables, fruits, maize, legumes, coffee, and tea",
    usageTip: "Useful when crops show nutrient deficiency symptoms or during high-demand stages.",
    safetyNote: "Should not replace good soil fertility management.",
    packSizes: "250ml, 500ml, 1L, 5L depending on stock",
    imageUrl: "/images/products/foliar-micronutrient.webp",
    featured: false,
  }),
  product(15, {
    name: "Calcium + Boron Foliar",
    category: "crop_nutrition",
    shortDescription: "Foliar nutrition support for flowering and fruit development.",
    description: "Calcium and boron foliar feeds are commonly used around flowering and fruit development.",
    specs: "Calcium and boron foliar nutrition",
    bestSuitedFor: "Tomatoes, capsicum, watermelon, fruit trees, and flowers",
    usageTip: "Often used around flowering and fruit development to support fruit quality.",
    safetyNote: "Avoid guarantee claims; results depend on farm conditions and correct use.",
    packSizes: "250ml, 500ml, 1L, 5L depending on stock",
    imageUrl: "/images/products/calcium-boron-foliar.webp",
    featured: false,
  }),
  product(16, {
    name: "Certified Hybrid Maize Seed",
    category: "seeds",
    shortDescription: "Certified maize seed options for different rainfall and maturity zones.",
    description: "Certified maize seed varieties should be selected according to rainfall, altitude, maturity period, and local agronomic advice.",
    specs: "Highland, medium-altitude, and dryland varieties depending on stock",
    bestSuitedFor: "Maize farmers across suitable Kenyan growing regions",
    usageTip: "Choose variety based on region, rainfall, altitude, and maturity period.",
    safetyNote: "Use certified seed only and follow seed-label guidance.",
    packSizes: "1kg, 2kg, 5kg, 10kg, 25kg depending on stock",
    imageUrl: "/images/products/certified-maize-seed.webp",
    featured: true,
  }),
  product(17, {
    name: "Certified Bean Seed",
    category: "seeds",
    shortDescription: "Certified bean varieties for rotation, intercropping, and market production.",
    description: "Certified bean seed is a key input for farmers growing beans as a food, cash, or rotation crop.",
    specs: "Certified bean varieties depending on market and region",
    bestSuitedFor: "Smallholder farms, intercropping with maize, and market beans",
    usageTip: "Good for farmers rotating with maize; legumes can improve soil nitrogen when well nodulated.",
    safetyNote: "Choose certified seed suited to region and season.",
    packSizes: "500g, 1kg, 2kg, 5kg depending on stock",
    imageUrl: "/images/products/certified-bean-seed.webp",
    featured: false,
  }),
  product(18, {
    name: "Green Gram Seed",
    category: "seeds",
    shortDescription: "Short-season legume seed for dry and semi-arid regions.",
    description: "Green gram is a short-season legume option for suitable dryland farming areas.",
    specs: "Certified green gram varieties depending on stock",
    bestSuitedFor: "Eastern Kenya and other dry or semi-arid regions where locally suitable",
    usageTip: "Market as a drought-tolerant legume option where locally suitable.",
    safetyNote: "Choose certified seed and follow local agronomic advice.",
    packSizes: "500g, 1kg, 2kg, 5kg depending on stock",
    imageUrl: "/images/products/green-gram-seed.webp",
    featured: false,
  }),
  product(19, {
    name: "Tomato Seed",
    category: "seeds",
    shortDescription: "Tomato seed options for open-field and greenhouse production.",
    description: "Tomato seed varieties should be selected based on production method, market type, disease tolerance, and local conditions.",
    specs: "Hybrid/open-pollinated depending on brand",
    bestSuitedFor: "Greenhouse and open-field horticulture",
    usageTip: "Stock varieties by market type: processing, fresh market, determinate, or indeterminate.",
    safetyNote: "Seed performance depends on variety selection, soil fertility, pest control, and crop management.",
    packSizes: "Small packets and tins depending on brand",
    imageUrl: "/images/products/tomato-seed.webp",
    featured: true,
  }),
  product(20, {
    name: "Kale / Sukuma Seed",
    category: "seeds",
    shortDescription: "Fast-moving leafy vegetable seed for households and market growers.",
    description: "Kale seed is a common stock item for kitchen gardens and commercial vegetable production.",
    specs: "Hybrid/open-pollinated depending on brand",
    bestSuitedFor: "Small gardens and commercial vegetable production",
    usageTip: "Fast-moving seed for Kenyan households and market gardeners.",
    safetyNote: "Choose seed suited to season and local disease pressure.",
    packSizes: "Small packets and tins depending on brand",
    imageUrl: "/images/products/kale-seed.webp",
    featured: false,
  }),
  product(21, {
    name: "Cabbage Seed",
    category: "seeds",
    shortDescription: "Cabbage seed options for vegetable farmers.",
    description: "Cabbage seed varieties differ by maturity period, head size, and growing conditions.",
    specs: "Hybrid/open-pollinated depending on brand",
    bestSuitedFor: "Cool/wet regions and vegetable farmers",
    usageTip: "Stock different maturity periods and head sizes.",
    safetyNote: "Choose certified seed and follow nursery management guidance.",
    packSizes: "Small packets and tins depending on brand",
    imageUrl: "/images/products/cabbage-seed.webp",
    featured: false,
  }),
  product(22, {
    name: "Onion Seed",
    category: "seeds",
    shortDescription: "Red and white onion seed varieties for commercial production.",
    description: "Onion seed supports dry-season irrigated farms and commercial vegetable growers.",
    specs: "Red/white onion varieties depending on stock",
    bestSuitedFor: "Dry-season irrigated farms and commercial growers",
    usageTip: "Needs careful nursery management and transplanting.",
    safetyNote: "Seed performance depends on nursery care, water, and crop management.",
    packSizes: "Small packets and tins depending on brand",
    imageUrl: "/images/products/onion-seed.webp",
    featured: false,
  }),
  product(23, {
    name: "Watermelon Seed",
    category: "seeds",
    shortDescription: "Watermelon seed options for warm lowlands and irrigated production.",
    description: "Watermelon seed is often paired with irrigation, mulch film, fungicides, and fruiting-stage nutrition.",
    specs: "Hybrid varieties depending on brand",
    bestSuitedFor: "Warm lowlands and irrigated production",
    usageTip: "Pair with drip irrigation, mulch, fungicides, and fruiting-stage fertilisers.",
    safetyNote: "Select certified seed suited to region and season.",
    packSizes: "Small packets and tins depending on brand",
    imageUrl: "/images/products/watermelon-seed.webp",
    featured: true,
  }),
  product(24, {
    name: "Registered Insecticide",
    category: "crop_protection",
    shortDescription: "PCPB-registered insect-control products matched to crop and pest.",
    description: "Insecticides should be selected by target pest, crop label, active ingredient, formulation, and registration status.",
    specs: "Contact or systemic insecticide depending on stock",
    bestSuitedFor: "Caterpillars, aphids, whiteflies, thrips, and other labelled pests depending on product",
    usageTip: "Match pest and crop to the official label; avoid blanket advice.",
    safetyNote: "Use only as directed on the official product label and wear recommended PPE.",
    packSizes: "Small packs, 100ml, 250ml, 500ml, 1L depending on product",
    imageUrl: "/images/products/registered-insecticide.webp",
    featured: true,
    activeIngredient: "Varies by registered product",
    formulation: "EC, SC, WP, WG, SL or other label formulation",
    targetUse: "Labelled insects only",
    registeredCropUse: "Only crops shown on the official label",
    pcpbStatus: "Must be confirmed before listing exact product",
    phi: "Follow official label",
    rei: "Follow official label",
    ppe: "Gloves, mask/respirator where required, goggles, boots, and protective clothing",
    storageWarning: "Keep locked away from children, food, animals, and water sources",
  }),
  product(25, {
    name: "Registered Fungicide",
    category: "crop_protection",
    shortDescription: "PCPB-registered fungicide options for labelled crop diseases.",
    description: "Fungicides should be chosen according to disease target, crop label, formulation, and mode of action.",
    specs: "Protectant/contact or systemic fungicide depending on stock",
    bestSuitedFor: "Tomatoes, potatoes, onions, vegetables, and horticulture depending on label",
    usageTip: "Wet or humid conditions increase disease pressure; use only labelled products.",
    safetyNote: "Observe product label, PPE, pre-harvest interval, and re-entry interval.",
    packSizes: "Small packs, 100g, 250g, 500g, 1kg depending on product",
    imageUrl: "/images/products/registered-fungicide.webp",
    featured: true,
    activeIngredient: "Varies by registered product",
    formulation: "WP, WG, SC, EC or other label formulation",
    targetUse: "Labelled fungal diseases only",
    registeredCropUse: "Only crops shown on the official label",
    pcpbStatus: "Must be confirmed before listing exact product",
    phi: "Follow official label",
    rei: "Follow official label",
    ppe: "Gloves, mask/respirator where required, goggles, boots, and protective clothing",
    storageWarning: "Store locked, dry, and away from food, feed, children, and animals",
  }),
  product(26, {
    name: "Registered Herbicide",
    category: "crop_protection",
    shortDescription: "PCPB-registered weed-control products matched to crop/site and weed type.",
    description: "Herbicides may be selective or non-selective and must be matched to crop, site, weed type, and timing.",
    specs: "Selective or non-selective herbicide depending on stock",
    bestSuitedFor: "Land preparation, maize fields, paths, or labelled crops/sites depending on product",
    usageTip: "Avoid spray drift and match product to crop growth stage and weed type.",
    safetyNote: "Wrong timing or crop mismatch can damage crops; follow label exactly.",
    packSizes: "250ml, 500ml, 1L, 5L depending on product",
    imageUrl: "/images/products/registered-herbicide.webp",
    featured: true,
    activeIngredient: "Varies by registered product",
    formulation: "SL, EC, SC, WG or other label formulation",
    targetUse: "Labelled weeds only",
    registeredCropUse: "Only crops/sites shown on the official label",
    pcpbStatus: "Must be confirmed before listing exact product",
    phi: "Follow official label",
    rei: "Follow official label",
    ppe: "Gloves, boots, protective clothing, and mask/respirator where required",
    storageWarning: "Store securely away from children, animals, food, and water sources",
  }),
  product(27, {
    name: "Biopesticide / Neem-Based Product",
    category: "crop_protection",
    shortDescription: "Biological or neem-based crop protection for IPM-oriented farmers.",
    description: "Biopesticide and neem-based products can support integrated pest management where products are properly registered and labelled.",
    specs: "Active organism or neem/azadirachtin-based ingredient depending on brand",
    bestSuitedFor: "Organic-oriented farmers, vegetable growers, and IPM programmes",
    usageTip: "Stock only verified registered products and explain storage conditions clearly.",
    safetyNote: "Natural-origin products still require label-based handling and application.",
    packSizes: "100ml, 250ml, 500ml, 1L depending on product",
    imageUrl: "/images/products/biopesticide-neem.webp",
    featured: false,
    activeIngredient: "Varies by registered product",
    formulation: "Varies by label",
    targetUse: "Labelled pests only",
    registeredCropUse: "Only crops shown on the official label",
    pcpbStatus: "Must be confirmed before listing exact product",
    phi: "Follow official label",
    rei: "Follow official label",
    ppe: "Follow official label; gloves and protective clothing recommended",
    storageWarning: "Follow storage conditions, especially for biological products",
  }),
  product(28, {
    name: "Knapsack Sprayer",
    category: "tools",
    shortDescription: "Manual sprayer for pesticide, foliar feed, and farm applications.",
    description: "Knapsack sprayers are practical tools for smallholder and horticultural farms.",
    specs: "16L or 20L manual sprayer depending on stock",
    bestSuitedFor: "Smallholder farms, vegetable farms, and maize farms",
    usageTip: "Sell with PPE, measuring cup, and correct nozzle advice.",
    safetyNote: "Clean after use and avoid mixing herbicide and crop-protection use without proper cleaning.",
    packSizes: "16L, 20L depending on stock",
    imageUrl: "/images/products/knapsack-sprayer.webp",
    featured: true,
  }),
  product(29, {
    name: "PPE Kit",
    category: "safety",
    shortDescription: "Protective gear for safer pesticide and farm input handling.",
    description: "PPE helps farmers reduce exposure risk when handling pesticides, foliar feeds, and other farm inputs.",
    specs: "Gloves, mask/respirator, goggles, gumboots, and overalls depending on kit",
    bestSuitedFor: "Anyone handling pesticides or spraying farm inputs",
    usageTip: "Strongly recommend with every pesticide purchase.",
    safetyNote: "PPE does not replace label instructions; always follow product safety directions.",
    packSizes: "Individual items and bundled kits depending on stock",
    imageUrl: "/images/products/ppe-kit.webp",
    featured: true,
  }),
  product(30, {
    name: "Seedling Trays + Cocopeat",
    category: "nursery",
    shortDescription: "Nursery supplies for raising healthy vegetable seedlings.",
    description: "Seedling trays and cocopeat support uniform seedling production for vegetable nurseries and kitchen gardens.",
    specs: "128-cell, 200-cell, or 288-cell trays with cocopeat/potting media",
    bestSuitedFor: "Tomato, cabbage, capsicum, sukuma wiki, and vegetable seedlings",
    usageTip: "Pair with quality seed, clean water, and nursery hygiene.",
    safetyNote: "Use clean media and avoid contaminated nursery materials.",
    packSizes: "Individual trays, bundles, and cocopeat blocks depending on stock",
    imageUrl: "/images/products/seedling-trays-cocopeat.webp",
    featured: true,
  }),
  product(31, {
    name: "Drip Irrigation Kit (1/8 Acre)",
    category: "irrigation",
    shortDescription: "Complete drip kit for water-efficient horticulture on a 1/8 acre plot.",
    description: "Drip irrigation delivers water directly to crop roots, cutting water use by up to 40% while improving yields. Suited to vegetables, fruits, and high-value horticulture across Kenyan farms.",
    specs: "Mainline, sub-mains, drip lines (16mm), filter, connectors, and fittings",
    bestSuitedFor: "Tomatoes, onions, capsicums, kale, watermelon, and other horticulture",
    usageTip: "Pair with a clean water source and consistent water pressure. Flush lines weekly to prevent clogging.",
    safetyNote: "Filter the water source to avoid blocked emitters. Check connections regularly.",
    packSizes: "1/8 acre, 1/4 acre, 1/2 acre, and 1 acre kits depending on stock",
    imageUrl: "/images/products/drip-irrigation-kit.webp",
    featured: true,
  }),
  product(32, {
    name: "HDPE Water Storage Tank (1000L)",
    category: "irrigation",
    shortDescription: "Durable plastic water tank for farm water storage and rainwater harvesting.",
    description: "HDPE water tanks store harvested rainwater, borehole, or piped water for irrigation and farm use. UV-stabilised for outdoor durability under Kenyan sun.",
    specs: "High-density polyethylene, UV-stabilised, food-grade",
    bestSuitedFor: "Farm water storage, livestock water supply, rainwater harvesting, drip irrigation reservoirs",
    usageTip: "Place on a flat, stable base. Clean once or twice a year to prevent algae and sediment build-up.",
    safetyNote: "Keep covered to prevent contamination, mosquito breeding, and child safety risks.",
    packSizes: "500L, 1000L, 2000L, 3000L, 5000L, and 10000L depending on stock",
    imageUrl: "/images/products/water-tank.webp",
    featured: false,
  }),
  product(33, {
    name: "Garden Hose & Sprinkler Set",
    category: "irrigation",
    shortDescription: "Garden hose with sprinkler attachments for vegetable plots and nurseries.",
    description: "Flexible garden hose with sprinkler attachments suits kitchen gardens, vegetable nurseries, and small-scale flower beds.",
    specs: "Reinforced PVC hose, 1/2 inch or 3/4 inch, with brass/plastic sprinkler nozzles",
    bestSuitedFor: "Kitchen gardens, vegetable plots, nurseries, dairy yards",
    usageTip: "Disconnect and store coiled in shade after use to extend hose life.",
    safetyNote: "Avoid kinking the hose; replace cracked sections to prevent leaks.",
    packSizes: "15m, 25m, 50m, and 100m lengths depending on stock",
    imageUrl: "/images/products/garden-hose-sprinkler.webp",
    featured: false,
  }),
  product(34, {
    name: "Solar Water Pump",
    category: "irrigation",
    shortDescription: "Solar-powered surface water pump for off-grid irrigation.",
    description: "Solar water pumps draw water from shallow wells, rivers, or tanks for irrigation without relying on grid electricity or fuel. Ideal for remote farms.",
    specs: "Solar panel + DC pump, surface mounted, suitable for shallow water sources",
    bestSuitedFor: "Off-grid farms, smallholder irrigation, livestock water supply",
    usageTip: "Position the solar panel for maximum sun exposure. Pump output varies with sunlight strength.",
    safetyNote: "Install electrical connections according to the supplier's wiring diagram.",
    packSizes: "Small (100W), medium (200W), and larger configurations depending on stock",
    imageUrl: "/images/products/solar-water-pump.webp",
    featured: true,
  }),
  product(35, {
    name: "PICS Hermetic Storage Bags",
    category: "post_harvest",
    shortDescription: "Triple-layer hermetic bags for chemical-free grain storage.",
    description: "PICS (Purdue Improved Crop Storage) bags use three layers to create an airtight seal that stops weevils, aflatoxin growth, and grain loss without using pesticides — a leading solution for smallholder grain storage in Kenya.",
    specs: "Three-layer hermetic bag, 50kg or 100kg capacity",
    bestSuitedFor: "Maize, beans, cowpeas, sorghum, millet, and other grains/legumes",
    usageTip: "Dry grain to 13% moisture before storage. Seal each layer tightly and store off the ground.",
    safetyNote: "Inspect bags for damage before reuse. Replace torn bags to maintain the hermetic seal.",
    packSizes: "50kg and 100kg bags, sold individually or in bundles",
    imageUrl: "/images/products/pics-bags.webp",
    featured: true,
  }),
  product(36, {
    name: "Tarpaulin / Drying Sheet",
    category: "post_harvest",
    shortDescription: "Heavy-duty tarpaulin for grain drying and crop protection.",
    description: "Tarpaulins are used to dry maize, beans, and other crops on a clean surface after harvest, reducing aflatoxin risk and contamination. Also used to cover stored produce.",
    specs: "Reinforced polyethylene, UV-treated, with reinforced eyelets",
    bestSuitedFor: "Grain drying, crop covers, market produce protection, farm storage",
    usageTip: "Spread on flat, clean ground in full sun. Turn grain regularly for even drying.",
    safetyNote: "Inspect for tears and store dry to extend lifespan.",
    packSizes: "10×10ft, 15×15ft, 20×20ft, and larger sizes depending on stock",
    imageUrl: "/images/products/tarpaulin.webp",
    featured: false,
  }),
  product(37, {
    name: "Manual Maize Sheller",
    category: "post_harvest",
    shortDescription: "Hand-crank sheller for fast, low-cost maize threshing.",
    description: "A manual maize sheller separates grain from the cob far faster than hand shelling, reducing labour and improving grain quality. Suited to smallholder and household-scale post-harvest operations.",
    specs: "Hand-cranked metal sheller, durable steel construction",
    bestSuitedFor: "Smallholder maize farmers, household use, post-harvest cooperatives",
    usageTip: "Shell maize when grain is fully dry. Clean and oil moving parts after each season.",
    safetyNote: "Keep hands clear of moving parts during operation.",
    packSizes: "Single units; motorised versions available on request",
    imageUrl: "/images/products/maize-sheller.webp",
    featured: false,
  }),
  product(38, {
    name: "Plastic Storage Crates",
    category: "post_harvest",
    shortDescription: "Stackable plastic crates for vegetable and fruit transport.",
    description: "Plastic crates protect tomatoes, onions, capsicums, and other fresh produce during storage and transport, reducing post-harvest losses compared to sacks.",
    specs: "Stackable HDPE crates with ventilation, food-grade",
    bestSuitedFor: "Tomato, onion, capsicum, fruit, and vegetable transport and storage",
    usageTip: "Stack carefully to avoid crushing the bottom layers. Wash crates between uses.",
    safetyNote: "Use food-grade crates only for produce contact.",
    packSizes: "Standard, large, and extra-large sizes depending on stock",
    imageUrl: "/images/products/storage-crates.webp",
    featured: true,
  }),
];
